name: hyper_webview_flutter
description: Flutter Library to enhance Juspay's Hyper Checkout Experience for Payment Links opened in WebView.
version: 0.0.1
homepage: https://juspay.in

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  plugin:
    platforms:
      android:
        package: in.juspay.hyper_webview_flutter
        pluginClass: HyperWebviewFlutterPlugin
